### ISSUE TITLE
[FR] database import command

### ISSUE THREAD

**Issue by mattstein** [pixelandtonic/nitro#1]
Thinking of something like DDEV’s `import-db`, which without any arguments asks you to point to a database. Also supports a `--src` argument for the fast (non-interactive) lane.

Others mentioned adding a flag (maybe `--support`) that could parse the dump for the table prefix and adjust `.env` accordingly.

**Comment by jasonmccallister** [comment]
@mattstein this was released with https://github.com/pixelandtonic/nitro/releases/tag/0.9.2
