### ISSUE TITLE
info command weirdness

### ISSUE THREAD

**Issue by angrybrad** [pixelandtonic/nitro#46]
If you have multiple VMs running and you run `nitro info`, it will only display the first VM.

You have to explicitly pass in `--machine` to see the 2nd VM's info.

Maybe `nitro info` should return all VM's by default and if you want just one, pass in the `--machine` flag?

Or maybe once https://github.com/pixelandtonic/nitro/issues/45 is implemented, and it's in the context of a project, it returns just that project's info unless you pass in a `--all`?

alternatively, vagrant has a `status` to get a per-project status and separate `global-status` to get all project statuses, but not sure that's the best way.

**Comment by jasonmccallister** [comment]
Not sure this is relevant anymore?

**Comment by angrybrad** [comment]
Nope.
