### ISSUE TITLE
Add auto-update check to nitro

### ISSUE THREAD

**Issue by angrybrad** [pixelandtonic/nitro#59]

**Comment by angrybrad** [comment]
Auto-self updating

**Comment by jasonmccallister** [comment]
I'm going to wrap this in a `version` command. This will display the currently installed version as well as check GitHub to see if there is a newer release (e.g the latest).

What do you think about having a flag `version --update` that will perform the download and print the steps to move into the bin directory.

**Comment by jasonmccallister** [comment]
scratching what I said earlier, we are going to stick to a common name of `self-update` which will download the release into /tmp and print the step to mv the file.

However, this would not be required for brew users.

**Comment by jasonmccallister** [comment]
Closing this, nitro version will display the latest version and there is a self-update command
