### ISSUE TITLE
Nitro context/info

### ISSUE THREAD

**Issue by angrybrad** [pixelandtonic/nitro#61]
Both commands share a lot of overlapping information.

We should consider combining them (probably into info).  If we think it gets to be too much information to display, could considering displaying basic information with `nitro info` and have a `--all` or `--advanced` flag to display all info.

**Comment by jasonmccallister** [comment]
`context` is similar to the `kubectl` command that displays the current configuration context or file. This lacks the Multipass specific information such as IP and mounted directories. 

Might be a good idea to merge, but they are different in purpose. I'll defer to your judgement 👍

**Comment by angrybrad** [comment]
> but they are different in purpose

Kinda... name, disk info, memory info, mount info overlap between them and they are both displaying similar config/metric data about the machine.

I say we just merge it all into `nitro info`.

**Comment by angrybrad** [comment]
Meh... this has grown on me.
